---
apiVersion: v1
kind: Service
metadata: 
  name: backend-lb
  labels:
    app: backend
  namespace: annika
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80