apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: annika
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi