---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template: 
    metadata:
      name: postgres
      labels:
        app: postgres
    spec: 
      volumes: 
        - name: pvc-postgres
          persistentVolumeClaim:
            claimName: pvc-postgres
      containers:
        - name: basic3tier
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: basic3tier
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin123
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-postgres
