---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-annika
  namespace: annika
spec:
  storageClassName: efs-sc
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0240564643cdec352::fsap-007d2ddd8f0e251ec