- name: Deploy frontend
  hosts: frontend
  become: true
  tasks:
    - name: Copy Dockerfile to host
      ansible.builtin.copy:
        src: ../docker/ui
        dest: /home/ubuntu

    - name: Build frontend
      community.docker.docker_image_build:
        name: frontend:latest
        path: /home/ubuntu/ui
        rebuild: always
        args: 
          LOADBALANCER: "alb-main-2092443240.eu-central-1.elb.amazonaws.com"

    - name: Start frontend
      community.docker.docker_container:
        name: frontend
        image: frontend:latest
        state: started
        recreate: true
        published_ports:
          - 80:80
          