webservers:
  hosts: 
    frontend: 
      ansible_host: 52.57.107.204
    backend:
      ansible_host: 3.72.113.128

databases:
  hosts:
    postgres: 
      ansible_host: 3.127.237.53

all:
  vars:
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_private_key_file: ../annika-mykey.pem
  