loadbalancers:
  hosts: 
    loadbalancer: 
      ansible_host: 18.194.129.47

webservers:
  hosts: 
    frontend: 
      ansible_host: 192.168.1.151
    backend:
      ansible_host: 192.168.2.119

databases:
  hosts:
    postgres: 
      ansible_host: 192.168.3.96

private:
  children:
    webservers:
    databases:
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -i ../annika-mykey.pem ubuntu@18.194.129.47 nc %h 22"'

all:
  vars:
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_private_key_file: ../annika-mykey.pem
  