webservers:
  hosts: 
    frontend: 
      ansible_host: 3.66.171.153
    backend:
      ansible_host: 18.194.197.41

databases:
  hosts:
    postgres: 
      ansible_host: 3.76.134.121

all:
  vars:
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_private_key_file: ../annika-mykey.pem
  