name: Build backend
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps: 
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
      - name: Checkout Repository
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/docker-login#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Create and boot a builder using by default the docker-container driver. This is a recommended step by docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build and push the image to Docker hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/Basic3TierAPI:latest
          build-args: |
            SONAR_PRJ_KEY=
            SONAR_TOKEN=${{secrets.SONAR_TOKEN}}
            SONAR_HOST=${{vars.SONAR_HOST}}

      


