name: Alter configmap

on:
  push:
    branches: [ "kubernetes-cicd" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
            aws-region: eu-central-1
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                
      - name: Configure cluster access
        run: aws eks update-kubeconfig --region eu-central-1 --name team1-eks-cluster 
                
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Apply database and backend kubernetes manifest files
        run: |
          kubectl apply -f database-clusterip.yml
          kubectl apply -f database-deployment.yml
          kubectl apply -f backend-loadbalancer.yml
          kubectl apply -f backend-deployment.yml
      
      - name: Run kubectl get svc
        run: kubectl -n annika get svc backend-lb -o jsonpath=/'{.status.loadBalancer.ingress[0].hostname}'

      - name: Export to Backend
        run: |
          export BACKEND_HOSTNAME=$(kubectl -n annika get svc backend-lb -o jsonpath=/'{.status.loadBalancer.ingress[0].hostname}')
          echo $BACKEND_HOSTNAME
        
      - name: Alter and apply configmap
        run: |
          export BACKEND_HOSTNAME=$(kubectl -n annika get svc backend-lb -o jsonpath=/'{.status.loadBalancer.ingress[0].hostname}')
          envsubst < frontend-configmap.yml | kubectl apply -f -
          cat frontend-configmap.yml